# Generated by Django 6.0 on 2025-12-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalbook',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
