# Generated by Django 5.2.7 on 2025-11-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_record', '0002_alter_purchasevoucher_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasevoucher',
            name='previous_due',
        ),
    ]
