# Generated by Django 5.2.7 on 2025-11-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_record', '0003_remove_purchasevoucher_previous_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='item_price',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='weight',
            field=models.FloatField(choices=[(25, '25'), (50, '50'), (26, '26')], default=0.0, max_length=10),
        ),
    ]
