# Generated by Django 5.2.7 on 2025-11-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_record', '0004_alter_purchaseitem_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='is_purchased_in_cash',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
