# Generated by Django 5.2.7 on 2025-11-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_record', '0005_purchasevoucher_is_purchased_in_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
