# Generated by Django 5.2.7 on 2025-10-31 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_record', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, max_length=400, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('account_type', models.CharField(choices=[('Bank', 'Bank'), ('Vendor', 'Vendor'), ('Customer', 'Customer')], default='Customer', max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit'), ('Balanced', 'Balanced')], default='Balanced', max_length=50)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_record.purchasevoucher')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('debit', models.FloatField(default=0.0)),
                ('credit', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, choices=[('Dr', 'Debit'), ('Cr', 'Credit'), ('Balanced', 'Balanced')], default='Balanced', max_length=50, null=True)),
                ('date', models.DateField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.ledger')),
            ],
        ),
    ]
