# Generated by Django 5.2.7 on 2025-10-31 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('purchase_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='purchase_voucher',
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_record.purchasevoucher'),
        ),
    ]
