# Generated by Django 5.2.7 on 2025-11-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0003_alter_deliveryorder_is_paid_and_more'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sell_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_order.deliveryorder'),
        ),
    ]
