# Generated by Django 5.2.7 on 2025-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_transaction_sell_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
