# Generated by Django 5.2.7 on 2025-10-31 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_ledger_purchase_voucher_and_more'),
        ('purchase_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchase_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_record.purchasevoucher', unique=True),
        ),
    ]
