# Generated by Django 5.2.7 on 2025-11-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_transaction_purchase_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
