# Generated by Django 6.0 on 2025-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_ledger_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
