# Generated by Django 5.2.7 on 2025-11-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_transaction_purchase_voucher'),
        ('purchase_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchase_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_record.purchasevoucher'),
        ),
    ]
