# Generated by Django 5.2.7 on 2025-12-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='bank_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
