# Generated by Django 5.2.7 on 2025-12-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_cashbook_bank_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
