# Generated by Django 5.2.7 on 2025-12-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0003_alter_cashbook_date_alter_cashtransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='is_bank',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
