# Generated by Django 5.2.7 on 2025-12-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0004_cashtransaction_is_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
