# Generated by Django 6.0 on 2025-12-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0005_cashtransaction_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransaction',
            name='balance',
        ),
    ]
