# Generated by Django 5.2.7 on 2025-11-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.FloatField(choices=[(26.0, '26 KG'), (25.0, '25 KG'), (50.0, '50 KG')], default='25.0'),
        ),
    ]
