# Generated by Django 5.2.7 on 2025-11-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='unit_label',
            field=models.CharField(blank=True, choices=[('Kg', 'Kilogram')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='saleslog',
            name='weight',
            field=models.FloatField(blank=True, choices=[(26.0, '26 KG'), (50.0, '50 KG'), (25.0, '25 KG')], null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.FloatField(choices=[(26.0, '26 KG'), (50.0, '50 KG'), (25.0, '25 KG')], default='25.0'),
        ),
    ]
