# Generated by Django 5.2.7 on 2025-11-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.FloatField(choices=[(50.0, '50 KG'), (25.0, '25 KG'), (26.0, '26 KG')], default='25.0'),
        ),
    ]
