# Generated by Django 5.2.7 on 2025-12-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_saleslog_unit_label_saleslog_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.FloatField(choices=[(50.0, '50 KG'), (26.0, '26 KG'), (25.0, '25 KG')], default='25.0'),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='weight',
            field=models.FloatField(blank=True, choices=[(50.0, '50 KG'), (26.0, '26 KG'), (25.0, '25 KG')], null=True),
        ),
    ]
