# Generated by Django 5.2.7 on 2025-11-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventory_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.FloatField(choices=[(25.0, '25 KG'), (50.0, '50 KG'), (26.0, '26 KG')], default='25.0'),
        ),
    ]
