# Generated by Django 6.0 on 2025-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_weight_alter_saleslog_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.FloatField(choices=[(25.0, '25 KG'), (26.0, '26 KG'), (50.0, '50 KG')], default='25.0'),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='weight',
            field=models.FloatField(blank=True, choices=[(25.0, '25 KG'), (26.0, '26 KG'), (50.0, '50 KG')], null=True),
        ),
    ]
