# Generated by Django 6.0 on 2025-12-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_saleslog_net_weight_alter_inventory_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.FloatField(choices=[(25.0, '25 KG'), (26.0, '26 KG'), (50.0, '50 KG')], default='25.0'),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='weight',
            field=models.FloatField(blank=True, choices=[(25.0, '25 KG'), (26.0, '26 KG'), (50.0, '50 KG')], null=True),
        ),
    ]
