# Generated by Django 6.0 on 2025-12-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_inventory_weight_alter_saleslog_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.FloatField(choices=[(50.0, '50 KG'), (25.0, '25 KG'), (26.0, '26 KG')], default='25.0'),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='weight',
            field=models.FloatField(blank=True, choices=[(50.0, '50 KG'), (25.0, '25 KG'), (26.0, '26 KG')], null=True),
        ),
    ]
