# Generated by Django 6.0 on 2026-02-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_alter_inventory_weight_alter_saleslog_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.FloatField(choices=[(25.0, '25 KG'), (50.0, '50 KG'), (26.0, '26 KG')], default='25.0'),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='weight',
            field=models.FloatField(blank=True, choices=[(25.0, '25 KG'), (50.0, '50 KG'), (26.0, '26 KG')], null=True),
        ),
    ]
