# Generated by Django 6.0 on 2025-12-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensebook',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='expensebook',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
