# Generated by Django 6.0 on 2025-12-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record', '0002_expensebook_amount_expensebook_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensebook',
            name='amount',
        ),
    ]
