# Generated by Django 6.0 on 2025-12-17 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record', '0004_expensetransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseBook',
            new_name='ExpenseType',
        ),
        migrations.RemoveField(
            model_name='expensetransaction',
            name='business',
        ),
        migrations.RemoveField(
            model_name='expensetransaction',
            name='expense_book',
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_expense_type_per_business'),
        ),
        migrations.DeleteModel(
            name='ExpenseTransaction',
        ),
    ]
