# Generated by Django 6.0 on 2025-12-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record', '0005_rename_expensebook_expensetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
