# Generated by Django 6.0 on 2025-12-17 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record', '0006_alter_expensetype_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseType',
            new_name='ExpenseLedger',
        ),
        migrations.RemoveConstraint(
            model_name='expenseledger',
            name='unique_expense_type_per_business',
        ),
        migrations.AddConstraint(
            model_name='expenseledger',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_expense_ledger_per_business'),
        ),
    ]
