# Generated by Django 6.0 on 2025-12-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record', '0007_rename_expensetype_expenseledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseledger',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
