# Generated by Django 6.0 on 2025-12-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record', '0009_expenseledgertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseledgertransaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
