# Generated by Django 6.0 on 2025-12-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_record', '0010_expenseledgertransaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseledgertransaction',
            name='balance',
        ),
    ]
