# Generated by Django 5.2.7 on 2025-12-08 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('addition', 'Addition'), ('withdrawal', 'Withdrawal')], max_length=50)),
                ('transaction_account', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=100)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital_management.capital')),
            ],
        ),
    ]
