# Generated by Django 5.2.7 on 2025-12-08 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='capitaltransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='capitaltransaction',
            name='transaction_account',
        ),
        migrations.RemoveField(
            model_name='capitaltransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='capital',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='capitaltransaction',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='capitaltransaction',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitaltransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='capitaltransaction',
            name='credit',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='capitaltransaction',
            name='debit',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='capitaltransaction',
            name='status',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='capitaltransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='capitaltransaction',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
