# Generated by Django 5.2.7 on 2025-11-05 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='grand_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='previous_due',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.FloatField(choices=[(25.0, '25 KG'), (50.0, '50 KG'), (26.0, '26 KG')], default=25.0)),
                ('unit_label', models.CharField(choices=[('Kg', 'Kilogram')], default='Kg', max_length=10)),
                ('total_weight', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery_order.deliveryorder')),
            ],
        ),
    ]
