# Generated by Django 5.2.7 on 2025-11-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0002_deliveryorder_date_deliveryorder_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='weight',
            field=models.FloatField(choices=[(26.0, '26 KG'), (50.0, '50 KG'), (25.0, '25 KG')], default=25.0),
        ),
    ]
