# Generated by Django 5.2.7 on 2025-11-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0003_alter_deliveryorder_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='due_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='payment_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='weight',
            field=models.FloatField(choices=[(26.0, '26 KG'), (25.0, '25 KG'), (50.0, '50 KG')], default=25.0),
        ),
    ]
