# Generated by Django 6.0 on 2025-12-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0024_alter_deliveryorderitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='weight',
            field=models.FloatField(choices=[(50.0, '50 KG'), (26.0, '26 KG'), (25.0, '25 KG')], default=25.0),
        ),
    ]
