# Generated by Django 6.0 on 2026-02-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0039_alter_deliveryorderitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='weight',
            field=models.FloatField(choices=[(25.0, '25 KG'), (26.0, '26 KG'), (50.0, '50 KG')], default=25.0),
        ),
    ]
